project:
  type: website

website:
  title: "Sean Lewis"
  description: "This is Sean Lewis personal Blog."
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/seanlewis08
      - icon: linkedin
        href: https://www.linkedin.com/in/selew/
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css



