project:
  type: website
  output-dir: docs

website:
  title: "Sean Lewis"
  description: "Data Scientist | Personal site & blog"
  navbar:
    right:
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/seanlewis08
      - icon: linkedin
        href: https://www.linkedin.com/in/selew/

format:
  html:
    theme:
      - cosmo
    css: styles.css
    include-after-body:
      text: |
        <script src="animations.js"></script>



