<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sean Lewis">
<meta name="dcterms.date" content="2026-03-07">
<meta name="description" content="DML combines Neyman orthogonal scores with cross-fitting to enable valid statistical inference about low-dimensional causal parameters while using flexible ML methods to estimate high-dimensional nuisance functions. This review covers the theory, two simulation illustrations, and three empirical applications including staggered adoption designs and non-tabular text data.">

<title>Introduction to Double/Debiased Machine Learning – Sean Lewis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sean Lewis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/seanlewis08"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/selew/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-gist" id="toc-the-gist" class="nav-link active" data-scroll-target="#the-gist">The Gist</a></li>
  <li><a href="#why-it-matters-now" id="toc-why-it-matters-now" class="nav-link" data-scroll-target="#why-it-matters-now">Why It Matters Now</a></li>
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How It Works</a>
  <ul class="collapse">
  <li><a href="#the-partially-linear-model-as-workhorse" id="toc-the-partially-linear-model-as-workhorse" class="nav-link" data-scroll-target="#the-partially-linear-model-as-workhorse">The Partially Linear Model as Workhorse</a></li>
  <li><a href="#why-non-orthogonal-scores-fail" id="toc-why-non-orthogonal-scores-fail" class="nav-link" data-scroll-target="#why-non-orthogonal-scores-fail">Why Non-Orthogonal Scores Fail</a></li>
  <li><a href="#why-cross-fitting-is-also-necessary" id="toc-why-cross-fitting-is-also-necessary" class="nav-link" data-scroll-target="#why-cross-fitting-is-also-necessary">Why Cross-Fitting Is Also Necessary</a></li>
  </ul></li>
  <li><a href="#key-results" id="toc-key-results" class="nav-link" data-scroll-target="#key-results">Key Results</a>
  <ul class="collapse">
  <li><a href="#iv-simulation-cross-fitting-eliminates-overfitting-bias" id="toc-iv-simulation-cross-fitting-eliminates-overfitting-bias" class="nav-link" data-scroll-target="#iv-simulation-cross-fitting-eliminates-overfitting-bias">IV Simulation: Cross-Fitting Eliminates Overfitting Bias</a></li>
  <li><a href="#ate-simulation-only-dml-achieves-nominal-coverage" id="toc-ate-simulation-only-dml-achieves-nominal-coverage" class="nav-link" data-scroll-target="#ate-simulation-only-dml-achieves-nominal-coverage">ATE Simulation: Only DML Achieves Nominal Coverage</a></li>
  <li><a href="#monopsony-application-learner-sensitivity" id="toc-monopsony-application-learner-sensitivity" class="nav-link" data-scroll-target="#monopsony-application-learner-sensitivity">Monopsony Application: Learner Sensitivity</a></li>
  </ul></li>
  <li><a href="#lineage" id="toc-lineage" class="nav-link" data-scroll-target="#lineage">Lineage</a></li>
  <li><a href="#rubber-ducking-the-jargon" id="toc-rubber-ducking-the-jargon" class="nav-link" data-scroll-target="#rubber-ducking-the-jargon">Rubber-Ducking the Jargon</a></li>
  <li><a href="#what-to-watch-out-for" id="toc-what-to-watch-out-for" class="nav-link" data-scroll-target="#what-to-watch-out-for">What to Watch Out For</a></li>
  <li><a href="#so-what" id="toc-so-what" class="nav-link" data-scroll-target="#so-what">So What?</a></li>
  <li><a href="#reproduction-implementation" id="toc-reproduction-implementation" class="nav-link" data-scroll-target="#reproduction-implementation">Reproduction &amp; Implementation</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Double/Debiased Machine Learning</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Econometrics</div>
  </div>
  </div>

<div>
  <div class="description">
    DML combines Neyman orthogonal scores with cross-fitting to enable valid statistical inference about low-dimensional causal parameters while using flexible ML methods to estimate high-dimensional nuisance functions. This review covers the theory, two simulation illustrations, and three empirical applications including staggered adoption designs and non-tabular text data.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sean Lewis </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>📄 <strong><a href="../../papers-hosted/intro-dml.pdf" target="_blank">Read the Full Paper</a></strong></p>
</blockquote>
<section id="the-gist" class="level2">
<h2 class="anchored" data-anchor-id="the-gist">The Gist</h2>
<p>You want to estimate a treatment effect, but the relationship between outcomes and confounders is complicated enough that you need machine learning to model it. Naively plugging ML estimates into your causal estimator breaks inference: your confidence intervals will be too narrow, your standard errors will be wrong, and your point estimates may be substantially biased. Double/Debiased Machine Learning (DML) fixes this.</p>
<p>The problem boils down to two sources of bias that arise when you replace parametric nuisance models with flexible ML estimators. <strong>Regularization bias</strong> occurs because ML methods (lasso, random forests, boosting) deliberately introduce bias to control variance, and that bias propagates into your target parameter estimate at rate √n.&nbsp;<strong>Overfitting bias</strong> arises because the same data used to fit the nuisance function is also used to evaluate the moment condition, creating a statistical dependence that prevents the product of estimation errors from being mean zero.</p>
<p>DML eliminates both problems with two ingredients. <strong>Neyman orthogonal scores</strong> are moment conditions whose derivative with respect to the nuisance parameter vanishes at the true value. This makes the target parameter estimator locally insensitive to small errors in nuisance estimation, neutralizing regularization bias. <strong>Cross-fitting</strong> partitions data into K folds, fits nuisance parameters on K−1 folds, and evaluates the score on the held-out fold. This breaks the dependence between nuisance estimation error and the score, neutralizing overfitting bias.</p>
<p>The resulting DML estimator is √n-consistent, asymptotically normal, and semiparametrically efficient under relatively weak conditions on the quality of nuisance estimation (convergence faster than n^{−1/4} in a suitable norm). Standard errors can be computed as if the nuisance functions were known, which is a remarkable practical simplification.</p>
<hr>
</section>
<section id="why-it-matters-now" class="level2">
<h2 class="anchored" data-anchor-id="why-it-matters-now">Why It Matters Now</h2>
<p>DML has become the standard framework for incorporating machine learning into causal inference in economics. The methodology was formalized in Chernozhukov et al.&nbsp;(2018), and this review by six of the leading contributors to the DML ecosystem (including the original <code>ddml</code> R package authors) provides the most comprehensive practical guide to date.</p>
<p>Three things make this review particularly valuable. First, it treats DML as a <strong>general estimation blueprint</strong> covering six different target parameters: linear regression coefficients, partially linear regression coefficients, linear IV, partially linear IV, average treatment effects, and average structural derivatives. Table 1 of the paper provides ready-to-use Neyman orthogonal scores for all six, making it a reference card for applied researchers.</p>
<p>Second, the empirical applications are unusually rich. The <strong>hospital admission</strong> example (Section 5) demonstrates DML in a staggered difference-in-differences design with conditional parallel trends, showing how cross-fitting variability can be diagnosed and summarized via median aggregation. The <strong>monopsony</strong> example (Section 6) uses DeBERTa v3 embeddings as covariates (replacing Doc2Vec), showing DML with non-tabular text data and revealing that DML estimates can range from −3.9 to 2.1 depending on the choice of nuisance estimator.</p>
<p>Third, the paper is explicit about <strong>what DML cannot do</strong>: it cannot tell you what parameters to estimate, it cannot validate your identifying assumptions, and results can be highly sensitive to the choice of ML learner. The monopsony application is a cautionary tale showing that 12 different learners yield qualitatively different conclusions about labor supply elasticity.</p>
<hr>
</section>
<section id="how-it-works" class="level2">
<h2 class="anchored" data-anchor-id="how-it-works">How It Works</h2>
<p>The DML algorithm is a three-step procedure that is the same regardless of the specific target parameter:</p>
<div class="cell" data-fig-width="8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph TD
    A["Data: {Wᵢ : i = 1,...,n}"] --&gt; B["Step 1: Randomly partition&lt;br/&gt;into K folds of equal size"]
    B --&gt; C["Step 2: For each fold k,&lt;br/&gt;fit nuisance η̂₋ₖ on&lt;br/&gt;all data EXCLUDING fold k"]
    C --&gt; D["Step 3: Construct DML estimator&lt;br/&gt;by solving cross-fitted&lt;br/&gt;score equation"]
    D --&gt; E["Estimate: θ̂_DML"]
    D --&gt; F["Standard errors:&lt;br/&gt;computed as if η₀ were known"]
    E --&gt; G["Valid inference:&lt;br/&gt;√n(θ̂ − θ₀) → N(0, Σ)"]
    F --&gt; G
</pre>
</div>
<p></p><figcaption> DML estimation and inference pipeline</figcaption> </figure><p></p>
</div>
</div>
</div>
<section id="the-partially-linear-model-as-workhorse" class="level3">
<h3 class="anchored" data-anchor-id="the-partially-linear-model-as-workhorse">The Partially Linear Model as Workhorse</h3>
<p>The paper repeatedly uses the partially linear regression model (PLR) as its core illustration, and it is the most common DML application in practice:</p>
<p><span class="math display">\[Y = \theta_0 D + g_0(X) + \varepsilon, \quad \text{E}[D\varepsilon] = \text{E}[\varepsilon|X] = 0\]</span></p>
<p>Here θ₀ is the treatment effect (a scalar), g₀(X) captures the arbitrarily complex relationship between controls and outcome, and the two zero-mean conditions are identifying assumptions.</p>
<p>Two moment conditions identify θ₀. The <strong>naive</strong> score uses only the outcome regression:</p>
<p><span class="math display">\[m_{\text{naive}}(W; \theta, \eta) = (Y - g(X) - \theta D) \cdot D\]</span></p>
<p>The <strong>Neyman orthogonal</strong> score partials out covariates from <em>both</em> Y and D (a generalization of Frisch-Waugh-Lovell):</p>
<p><span class="math display">\[m_{\text{PLM}}(W; \theta, \eta) = [(Y - \ell(X)) - \theta(D - r(X))] \cdot (D - r(X))\]</span></p>
<p>where ℓ(X) = E[Y|X] and r(X) = E[D|X]. Both scores identify the same θ₀. But only the second is Neyman orthogonal, meaning small errors in estimating ℓ and r have only second-order effects on θ̂. The naive score is not orthogonal because errors in g(X) that are correlated with D directly bias the estimate (the classic omitted variable problem in a new guise).</p>
</section>
<section id="why-non-orthogonal-scores-fail" class="level3">
<h3 class="anchored" data-anchor-id="why-non-orthogonal-scores-fail">Why Non-Orthogonal Scores Fail</h3>
<p>The Taylor expansion of the plug-in estimator around the true parameters reveals a first-order impact term (⋆):</p>
<p><span class="math display">\[\sqrt{n}(\hat{\theta} - \theta_0) = \underbrace{\text{CLT term}}_{\text{converges to normal}} + \underbrace{(\star) \text{: first-order nuisance impact}}_{\text{DML must eliminate this}} + \text{higher-order terms}\]</span></p>
<p>For Neyman orthogonal scores, the key derivative ∂m/∂η evaluated at η₀ is mean zero, so (⋆) vanishes under mild convergence conditions. For non-orthogonal scores, this derivative is generally <em>not</em> mean zero, making (⋆) of order √n times the nuisance estimation error, which can dominate the CLT term entirely.</p>
</section>
<section id="why-cross-fitting-is-also-necessary" class="level3">
<h3 class="anchored" data-anchor-id="why-cross-fitting-is-also-necessary">Why Cross-Fitting Is Also Necessary</h3>
<p>Even with a Neyman orthogonal score, (⋆) does not vanish if the nuisance estimator η̂ and the score are evaluated on the <em>same</em> data. The product (∂m/∂η)(η̂ − η₀) may not be mean zero due to statistical dependence, even when each factor is individually mean zero or converging. Cross-fitting breaks this dependence by construction: η̂₋ₖ is trained on data excluding fold k, so it is independent of the scores evaluated on fold k.</p>
<hr>
</section>
</section>
<section id="key-results" class="level2">
<h2 class="anchored" data-anchor-id="key-results">Key Results</h2>
<section id="iv-simulation-cross-fitting-eliminates-overfitting-bias" class="level3">
<h3 class="anchored" data-anchor-id="iv-simulation-cross-fitting-eliminates-overfitting-bias">IV Simulation: Cross-Fitting Eliminates Overfitting Bias</h3>
<p>The first simulation uses a many-instrument IV setting (200 instruments, 6 relevant, n = 1000). Without cross-fitting, both 2SLS and boosted trees are severely biased (average bias around 0.32–0.37) with zero confidence interval coverage. With cross-fitting, SSIV and DML with boosted trees are approximately unbiased with near-nominal coverage:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimator</th>
<th>Bias</th>
<th>Std. Dev.</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oracle IV (infeasible)</td>
<td>−0.008</td>
<td>0.077</td>
<td>0.957</td>
</tr>
<tr class="even">
<td>2SLS (no x-fit)</td>
<td>0.323</td>
<td>0.045</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>Boosted Trees (no x-fit)</td>
<td>0.374</td>
<td>0.037</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>SSIV (x-fit)</td>
<td>−0.033</td>
<td>0.173</td>
<td>0.938</td>
</tr>
<tr class="odd">
<td><strong>DML + Boosted Trees</strong></td>
<td><strong>−0.020</strong></td>
<td><strong>0.108</strong></td>
<td><strong>0.959</strong></td>
</tr>
</tbody>
</table>
<p>DML with boosted trees achieves lower variance than SSIV (0.108 vs 0.173) while maintaining coverage, reflecting the advantage of a flexible, regularized first stage.</p>
</section>
<section id="ate-simulation-only-dml-achieves-nominal-coverage" class="level3">
<h3 class="anchored" data-anchor-id="ate-simulation-only-dml-achieves-nominal-coverage">ATE Simulation: Only DML Achieves Nominal Coverage</h3>
<p>The ATE simulation is calibrated to the classic Poterba, Venti, and Wise (1995) 401(k) dataset (n = 9,915; true ATE ≈ 6,889). It compares six estimators varying in their use of Neyman orthogonal scores and cross-fitting:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimator</th>
<th>Neyman Orth.</th>
<th>Cross-Fit</th>
<th>Bias</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>DML (AIPW + x-fit)</strong></td>
<td><strong>Yes</strong></td>
<td><strong>Yes</strong></td>
<td><strong>47</strong></td>
<td><strong>0.945</strong></td>
</tr>
<tr class="even">
<td>AIPW (no x-fit)</td>
<td>Yes</td>
<td>No</td>
<td>142</td>
<td>0.911</td>
</tr>
<tr class="odd">
<td>RA + x-fit</td>
<td>No</td>
<td>Yes</td>
<td>595</td>
<td>0.834</td>
</tr>
<tr class="even">
<td>IPW + x-fit</td>
<td>No</td>
<td>Yes</td>
<td>756</td>
<td>0.851</td>
</tr>
<tr class="odd">
<td>RA (no x-fit)</td>
<td>No</td>
<td>No</td>
<td>644</td>
<td>0.815</td>
</tr>
<tr class="even">
<td>IPW (no x-fit)</td>
<td>No</td>
<td>No</td>
<td>747</td>
<td>0.853</td>
</tr>
</tbody>
</table>
<p>Only the DML estimator (combining both ingredients) achieves near-nominal 95% coverage. Dropping either ingredient degrades performance substantially.</p>
</section>
<section id="monopsony-application-learner-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="monopsony-application-learner-sensitivity">Monopsony Application: Learner Sensitivity</h3>
<p>In the Dube et al.&nbsp;(2020) reanalysis of monopsony power on Amazon MTurk, 12 candidate nuisance estimators (OLS, lasso, ridge, three random forest specs, three XGBoost specs, three neural nets) produce DML estimates of the labor supply elasticity ranging from −3.9 to 2.1. Stacking (model averaging via constrained least squares) produces a preferred estimate of −0.054 (s.e. = 0.020), consistent with the original study’s estimates in the 0.03–0.20 range. XGBoost specifications achieve cross-fitted R² values of 85%/74% for outcome/treatment, while neural networks achieve below 4%/22%, explaining their instability.</p>
<hr>
</section>
</section>
<section id="lineage" class="level2">
<h2 class="anchored" data-anchor-id="lineage">Lineage</h2>
<div class="cell" data-fig-width="8" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    A["Neyman (1959)&lt;br/&gt;Orthogonal scores"] --&gt; D["Chernozhukov et al. (2018)&lt;br/&gt;DML framework"]
    B["Frisch-Waugh-Lovell&lt;br/&gt;Partialling out"] --&gt; D
    C["Sample splitting&lt;br/&gt;Angrist &amp; Krueger (1995)"] --&gt; D
    E["Robinson (1988)&lt;br/&gt;Partially linear model"] --&gt; D
    D --&gt; F["ddml R package&lt;br/&gt;Wiemann et al. (2023)"]
    D --&gt; G["DoubleML Python&lt;br/&gt;Bach et al. (2024)"]
    D --&gt; H["This review:&lt;br/&gt;Ahrens et al. (2026)"]
    I["TMLE / van der Laan&lt;br/&gt;(2006, 2011)"] -.-&gt;|"Related"| D
    J["Robins et al. (2017)&lt;br/&gt;Debiased ML"] -.-&gt;|"Related"| D
</pre>
</div>
<p></p><figcaption> DML intellectual lineage</figcaption> </figure><p></p>
</div>
</div>
</div>
<p>The core DML framework was formalized in Chernozhukov, Chetverikov, Demirer, Duflo, Hansen, Newey, and Robins (2018). This review connects DML back to classical ideas: Neyman (1959) orthogonal scores, the Frisch-Waugh-Lovell theorem for partialling out, Robinson’s (1988) partially linear model, and split-sample IV estimation from Angrist and Krueger (1995). On the applied side, it builds on Dobkin et al.&nbsp;(2018) for hospital admission analysis, Sun and Abraham (2021) for staggered designs, and Dube et al.&nbsp;(2020) for monopsony estimation with text data.</p>
<hr>
</section>
<section id="rubber-ducking-the-jargon" class="level2">
<h2 class="anchored" data-anchor-id="rubber-ducking-the-jargon">Rubber-Ducking the Jargon</h2>
<p><strong>Neyman orthogonal score.</strong> A moment condition m(W; θ, η) whose expected derivative with respect to the nuisance parameter η vanishes at the true value η₀, in all directions. Formally: ∂/∂λ E[m(W; θ₀, η₀ + λΔη)]|_{λ=0} = 0 for all perturbations Δη. This means small errors in estimating η have only second-order effects on θ̂. In the PLR model, this corresponds to residualizing both Y and D on X before running the final regression, rather than only adjusting Y.</p>
<p><strong>Cross-fitting.</strong> A K-fold procedure where the data is randomly split into K roughly equal parts. For each fold k, nuisance parameters are estimated using all data <em>except</em> fold k, and the score for fold k is evaluated using those out-of-fold estimates. This is structurally identical to K-fold cross-validation but serves a different purpose: it ensures independence between nuisance estimation errors and the scores, which is necessary for valid inference.</p>
<p><strong>Regularization bias.</strong> Bias introduced when ML estimators trade off bias for variance (e.g., lasso shrinks coefficients toward zero, random forests average over limited-depth trees). In the DML context, this bias in nuisance estimation contaminates the target parameter estimate unless the score is Neyman orthogonal.</p>
<p><strong>Overfitting bias.</strong> Bias arising from the statistical dependence between nuisance estimation error and the data used to evaluate the moment condition. Unlike standard “overfitting” (inflated prediction accuracy), here overfitting in nuisance estimation leads to bias in the <em>target</em> parameter estimate. Cross-fitting breaks this dependence.</p>
<p><strong>AIPW (augmented inverse probability weighting).</strong> The doubly robust score for the ATE: it combines an outcome regression adjustment with inverse propensity weighting, and remains consistent if <em>either</em> the outcome model or the propensity score is correctly specified. It is the unique Neyman orthogonal score for the ATE (up to efficiency equivalence).</p>
<p><strong>Median aggregation.</strong> A strategy for addressing the algorithmic randomness introduced by cross-fitting: repeat the DML procedure S times with different random splits, then report the median point estimate and a standard error that accounts for both sampling uncertainty and split-to-split variation. This reduces dependence on any single random partition and serves as a diagnostic for stability.</p>
<p><strong>Super learner / stacking.</strong> A model averaging approach that combines multiple candidate ML learners into a weighted average, with weights chosen to minimize cross-validated prediction error. In the monopsony application, stacking assigns large weights only to XGBoost specifications, producing a DML estimate consistent across alternative selection strategies.</p>
<hr>
</section>
<section id="what-to-watch-out-for" class="level2">
<h2 class="anchored" data-anchor-id="what-to-watch-out-for">What to Watch Out For</h2>
<p><strong>Learner sensitivity is real and consequential.</strong> The monopsony application is a cautionary example: the same DML procedure with the same data produces labor supply elasticity estimates ranging from −3.9 to 2.1 depending on the nuisance learner. The theory tells you that DML delivers valid inference <em>if</em> the nuisance estimator converges at rate n^{−1/4}. In practice, there is no guarantee that any particular learner achieves this rate for your data. Always report results from multiple learners and use diagnostics (cross-fitted R², confidence with validation via CVC tests) to assess learner quality.</p>
<p><strong>Cross-fitting introduces algorithmic randomness.</strong> The DML estimator depends on the random partition into folds, and different splits can yield meaningfully different point estimates and standard errors in finite samples. The hospital admission application shows estimates for group 9’s first-period treatment effect ranging from 3,204 to 3,486 across five random splits (roughly 30% of the standard error). Repeat the procedure multiple times and report the median aggregate.</p>
<p><strong>Non-orthogonal scores fail silently.</strong> The IPW score for the ATE and the naive score for the PLR coefficient are not Neyman orthogonal. They will produce point estimates that may look reasonable, but the confidence intervals will systematically undercover. The ATE simulation shows IPW achieving only 85% coverage at the nominal 95% level, and the bias can be an order of magnitude larger than DML. There is no diagnostic that will tell you “this score is non-orthogonal” after the fact; you need to check the orthogonality condition analytically or use a known orthogonal score from Table 1.</p>
<p><strong>DML does not validate identifying assumptions.</strong> DML assumes you have already defined a target parameter and established the conditions under which it is identified from the observed data. For the ATE, this means overlap and unconfoundedness must hold. For the PLR coefficient, exogeneity conditions must hold. DML makes nuisance estimation flexible, not identification.</p>
<p><strong>Off-the-shelf ML can fail DML’s rate requirements.</strong> Random forests with default tuning may not converge fast enough for DML in high-dimensional settings (Chi et al., 2022). Deep regression trees may be pointwise inconsistent (Cattaneo, Klusowski, and Yu, 2025). No known method achieves the n^{−1/4} rate for fully nonparametric nuisance functions without additional structural assumptions. This is not a theoretical curiosity; it means DML results should be interpreted with caution when nuisance functions are highly complex.</p>
<hr>
</section>
<section id="so-what" class="level2">
<h2 class="anchored" data-anchor-id="so-what">So What?</h2>
<p>For applied researchers, the paper consolidates the practical DML workflow into a clear sequence. First, define your target parameter and verify identification. Second, select a Neyman orthogonal score (Table 1 provides six common ones). Third, choose K (typically 5–10), select candidate learners (always try multiple), and run the cross-fitted DML procedure. Fourth, repeat S times to assess split-to-split variability and report the median aggregate. Fifth, examine diagnostics: cross-fitted R² for nuisance performance, CVC p-values for learner comparison, and stacking weights for model combination.</p>
<p>The honest message of this review is that DML is powerful but not automatic. The framework gives you valid inference <em>when its conditions hold</em>, and the practical challenge is verifying that those conditions are approximately satisfied. Divergent estimates across learners, poor cross-fitted R² values, and high split-to-split variability are all warning signs that the DML conditions may not be met for your application.</p>
<p>For methodologists, the open problems are clear. Better guidance on which learners achieve sufficient convergence rates for which data structures. Better finite-sample corrections for small K and small n.&nbsp;Better handling of dependent data (panel settings, clustered observations). And better integration of DML with sensitivity analysis tools when identifying assumptions are questionable.</p>
<hr>
</section>
<section id="reproduction-implementation" class="level2">
<h2 class="anchored" data-anchor-id="reproduction-implementation">Reproduction &amp; Implementation</h2>
<p>The paper uses three software ecosystems:</p>
<p><strong>R (<code>ddml</code>):</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ddml)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Partially linear model with DML</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">ddml_plm</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> Y, <span class="at">D =</span> D, <span class="at">X =</span> X,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">learners =</span> <span class="fu">list</span>(<span class="st">"lasso"</span>, <span class="st">"rf"</span>, <span class="st">"xgboost"</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_folds =</span> <span class="dv">5</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_rep =</span> <span class="dv">10</span>  <span class="co"># median aggregation over 10 splits</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Python (<code>DoubleML</code>):</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> doubleml <span class="im">import</span> DoubleMLPLR, DoubleMLData</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>dml_data <span class="op">=</span> DoubleMLData(df, y_col<span class="op">=</span><span class="st">'Y'</span>, d_cols<span class="op">=</span><span class="st">'D'</span>, x_cols<span class="op">=</span>X_cols)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>dml_plr <span class="op">=</span> DoubleMLPLR(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    dml_data,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    ml_l<span class="op">=</span>RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">1000</span>, min_samples_leaf<span class="op">=</span><span class="dv">10</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    ml_m<span class="op">=</span>RandomForestRegressor(n_estimators<span class="op">=</span><span class="dv">1000</span>, min_samples_leaf<span class="op">=</span><span class="dv">10</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    n_folds<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    n_rep<span class="op">=</span><span class="dv">10</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>dml_plr.fit()</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dml_plr.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Stata (<code>ddml</code>):</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ddml init plm, <span class="fu">y</span>(Y) <span class="kw">d</span>(D) mname(m1)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ddml E[Y|X]: pystacked <span class="ot">$X</span>, <span class="dv">type</span>(<span class="kw">reg</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ddml E[D|X]: pystacked <span class="ot">$X</span>, <span class="dv">type</span>(<span class="kw">reg</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ddml crossfit, shortstack</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>ddml estimate, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Full replication code and additional examples are available at <a href="https://dmlguide.github.io">dmlguide.github.io</a>.</p>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Ahrens, A., Chernozhukov, V., Hansen, C., Kozbur, D., Schaffer, M. E., &amp; Wiemann, T. (2026). Introduction to Double/Debiased Machine Learning. <em>arXiv:2504.08324v2</em>.</p>
<p>Chernozhukov, V., Chetverikov, D., Demirer, M., Duflo, E., Hansen, C., Newey, W., &amp; Robins, J. (2018). Double/debiased machine learning for treatment and structural parameters. <em>The Econometrics Journal</em>, 21(1), C1–C68.</p>
<p>Dobkin, C., Finkelstein, A., Kluender, R., &amp; Notowidigdo, M. J. (2018). The economic consequences of hospital admissions. <em>American Economic Review</em>, 108(2), 308–352.</p>
<p>Dube, A., Jacobs, J., Naidu, S., &amp; Suri, S. (2020). Monopsony in online labor markets. <em>American Economic Review: Insights</em>, 2(1), 33–46.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="seanlewis08/blogComments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<script src="animations.js"></script>




</body></html>